version: '2'

services:

  elasticsearch:
    image: elasticsearch:6.5.2
    command: elasticsearch -Des.network.host=0.0.0.0
    ports:
      - "9200:9200"
      - "9300:9300"

  kibana:
    build: kibana/
    volumes:
      - ./kibana/config/:/opt/kibana/config/
    ports:
      - "5601:5601"
    links:
      - elasticsearch

  dockbeat:
    build: ./dockbeatbuild
    image: dockbeat
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ./config/:/etc/dockbeat
    links: 
      - elasticsearch
